export const photoTags = [
  "Covid-19",
  "Work From Home",
  "Technology",
  "Nature",
  "Wallpaper",
  "People",
  "Textures and Pattern",
  "Animals",
  "Travel",
  "Interiors",
  "Business and Work",
  "Food and Drink",
  "Film",
  "Architecture",
  "Spirituality",
  "Health and Wellness",
  "Fashion",
  "Experimental",
  "Art and Culture",
  "Current Events",
];
