export const LOAD_PHOTOS = "LOAD_PHOTOS";
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const LOAD_PHOTOS_FAILURE = "LOAD_PHOTOS_FAILURE";

export const PHOTOS_SEARCH = "PHOTOS_SEARCH"
export const PHOTOS_SEARCH_SUCCESS = "PHOTOS_SEARCH_SUCCESS"
export const PHOTOS_SEARCH_FAILURE = "PHOTOS_SEARCH_FAILURE"

export const LOAD_MORE_PHOTOS = "LOAD_MORE_PHOTOS"
export const LOAD_MORE_PHOTOS_SUCCESS = "LOAD_MORE_PHOTOS_SUCCESS"
export const LOAD_MORE_PHOTOS_FAILURE = "LOAD_MORE_PHOTOS_FAILURE"

export const LOAD_CLICKED_PHOTOTAGS = "LOAD_CLICKED_PHOTOTAGS"
export const LOAD_CLICKED_PHOTOTAGS_SUCCESS = "LOAD_CLICKED_PHOTOTAGS_SUCCESS"
export const LOAD_CLICKED_PHOTOTAGS_FAILURE = "LOAD_CLICKED_PHOTOTAGS_FAILURE"