export const LOAD_PHOTOS = "LOAD_PHOTOS";
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const LOAD_PHOTOS_FAILURE = "LOAD_PHOTOS_FAILURE";

export const PHOTOS_SEARCH = "PHOTOS_SEARCH"
export const PHOTOS_SEARCH_SUCCESS = "PHOTOS_SEARCH_SUCCESS"
export const PHOTOS_SEARCH_FAILURE = "PHOTOS_SEARCH_FAILURE"

export const LOAD_MORE_PHOTOS = "LOAD_MORE_PHOTOS"
export const LOAD_MORE_PHOTOS_SUCCESS = "LOAD_MORE_PHOTOS_SUCCESS"
export const LOAD_MORE_PHOTOS_FAILURE = "LOAD_MORE_PHOTOS_FAILURE"

export const LOAD_CLICKED_PHOTOTAGS = "LOAD_CLICKED_PHOTOTAGS"
export const LOAD_CLICKED_PHOTOTAGS_SUCCESS = "LOAD_CLICKED_PHOTOTAGS_SUCCESS"
export const LOAD_CLICKED_PHOTOTAGS_FAILURE = "LOAD_CLICKED_PHOTOTAGS_FAILURE"

export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN"
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESSS"
export const GET_ACCESS_TOKEN_FAILURE = "GET_ACCESS_TOKEN_FAILURE"

export const GET_USER = "GET_USER"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const LIKE_PHOTO = "LIKE_PHOTO"
export const LIKE_PHOTO_SUCCESS = "LIKE_PHOTO_SUCCESS"
export const LIKE_PHOTO_FAILURE = "LIKE_PHOTO_FAILURE"
export const UNLIKE_PHOTO = "UNLIKE_PHOTO"
export const UNLIKE_PHOTO_SUCCESS = "UNLIKE_PHOTO_SUCCESS"
export const UNLIKE_PHOTO_FAILURE = "UNLIKE_PHOTO_FAILURE"
export const UPDATE_PHOTO = "UPDATE_PHOTO"


export const LOGOUT_USER = "LOGOUT_USER"