export const LOAD_PHOTOS = "LOAD_PHOTOS";
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const LOAD_PHOTOS_FAILURE = "LOAD_PHOTOS_FAILURE";

export const PHOTOS_SEARCH = "PHOTOS_SEARCH"
export const PHOTOS_SEARCH_SUCCESS = "PHOTOS_SEARCH_SUCCESS"
export const LOAD_MORE_PHOTOS = "LOAD_MORE_PHOTOS"
